// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApiEntityFramework.Migrations
{
    [DbContext(typeof(DogsContext))]
    [Migration("20221115221918_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAllShots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 7,
                            Breed = "Beagle",
                            HasAllShots = true,
                            Name = "Daisy"
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            Breed = "Boxer",
                            HasAllShots = true,
                            Name = "Sadie"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Breed = "Basset Hound",
                            HasAllShots = false,
                            Name = "Belle"
                        },
                        new
                        {
                            Id = 4,
                            Age = 3,
                            Breed = "Mastiff",
                            HasAllShots = false,
                            Name = "Ellie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
