// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApiEntityFramework.Migrations
{
    [DbContext(typeof(DogsContext))]
    [Migration("20221117150839_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApiEntityFramework.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HasAllShots")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 7,
                            Breed = "Beagle",
                            Description = "Daisy is a cute dog with short black hair and loves people.",
                            HasAllShots = true,
                            Name = "Daisy"
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            Breed = "Boxer",
                            Description = "Large dog with big feet. Loves to chew shoes.",
                            HasAllShots = true,
                            Name = "Sadie"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Breed = "Basset Hound",
                            Description = "Great at playing fetch!",
                            HasAllShots = false,
                            Name = "Belle"
                        },
                        new
                        {
                            Id = 4,
                            Age = 3,
                            Breed = "Mastiff",
                            Description = "Big girl who loves the couch. Needs lots of space to play. Loves eating socks and tennis balls.",
                            HasAllShots = false,
                            Name = "Ellie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
